# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    # Cấu hình này rất quan trọng để rewrite (viết lại) đường dẫn
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    # Sử dụng IP public của máy chủ của bạn
    - host: app.139.59.253.95.nip.io
      http:
        paths:
          # QUY TẮC 1: GỬI YÊU CẦU API ĐẾN BACKEND
          # Sẽ khớp với '/api/users/signup'
          # và gửi '/users/signup' đến backend-service ở cổng 5000
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-service # Tên từ file service.yaml
                port:
                  number: 5000 # Cổng từ file service.yaml

          # QUY TẮC 2: GỬI MỌI THỨ CÒN LẠI ĐẾN FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
