# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    # XÓA BỎ TẤT CẢ annotation 'rewrite-target'
    # Chúng ta không cần nó nếu backend của bạn đã xử lý /api
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    # Sử dụng IP public và nip.io
    - host: app.139.59.253.95.nip.io
      http:
        paths:
          
          # QUY TẮC 1: BACKEND (Phải đặt TRƯỚC)
          # Gửi /api/users/signup -> backend-service:5000/api/users/signup
          - path: /api
            pathType: Prefix # Sẽ khớp với /api VÀ /api/bất-cứ-thứ-gì
            backend:
              service:
                name: backend-service
                port:
                  number: 5000 # Cổng từ service.yaml

          # QUY TẮC 2: FRONTEND (Phải đặt SAU)
          # Gửi / -> frontend-service:80/
          # Gửi /static/js/main...js -> frontend-service:80/static/js/main...js
          - path: /
            pathType: Prefix # Sẽ khớp với mọi thứ còn lại
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
